# Generated by Django 5.1.6 on 2025-03-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="score",
        ),
        migrations.AddField(
            model_name="match",
            name="ai_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="ocr_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="tfidf_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
