# Generated by Django 5.1.6 on 2025-03-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0003_creditrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
