# Generated by Django 5.1.6 on 2025-03-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0004_creditrequest_approved_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="ocr_text_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
